dz_20_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from main.apps import MainConfig
from main.views import IndexView, ProductListView, ContactView, ProductDetailView, RecordListView, RecordDetailView, \
    RecordCreateView, RecordUpdateView, RecordDeleteView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    VersionListView, CategoriesListView

app_name = MainConfig.name


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # path('', post_route)  # получение запроса из постмана
    path('contacts/', ContactView.as_view(), name='contacts'),  # Вывод url контакты  из views.py contacts
    path('products/', ProductListView.as_view(), name='products_list'),
    path('categories/', CategoriesListView.as_view(), name='categories_list'),
    path('version/', VersionListView.as_view(), name='version_list'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_item'), # url студента с переменной, в контроллере(views) так же указывается
    path('product/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('product/update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('product/delete/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='product_delete'),
    path('records/', RecordListView.as_view(), name='records_list'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_detail'),
    path('record/create/', never_cache(RecordCreateView.as_view()), name='record_create'),
    path('record/update/<int:pk>/', never_cache(RecordUpdateView.as_view()), name='record_update'),
    path('record/delete/<int:pk>/', never_cache(RecordDeleteView.as_view()), name='record_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileUpdateView, RegisterView, activate_user, page_after_registration, generate_new_password

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('activate/<str:token>/', activate_user, name='activate'),
    path('page_after_registration/<str:token>/', page_after_registration, name='page_after_registration'),
    path('profile/gennpassword', generate_new_password, name='generate_new_password'),
]

users/models.py
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser, UserManager as UserBaseManager
from django.db import models
from django.apps import apps
from main.models import NULLABLE


class UserCManager(UserBaseManager):   # переопределение модели для команды python manage.py createsuperuser (для
    # поля email)
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        email = GlobalUserModel.normalize_username(email)
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='страна', **NULLABLE)
    token = models.CharField(max_length=15, verbose_name='токен', **NULLABLE)
    token_time = models.DateTimeField(auto_now_add=True, verbose_name='время создания токена', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserCManager()

    def __str__(self):
        return f'{self.email}'

users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django import forms
from main.forms import FormStyleMixin
from users.models import User


class UserForm(FormStyleMixin, UserChangeForm):  # форма изменения данных пользователя
    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar', 'first_name', 'last_name', 'country',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # print(self.fields['password'])
        self.fields['password'].widget = forms.HiddenInput()  # скрывает password при заполнении


class UserRegisterForm(FormStyleMixin, UserCreationForm):  # форма регистрации
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'country',)

users/views.py
import secrets

from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, CreateView

from dz_20_1 import settings
from services.confirm_account import confirm_account
from users.forms import UserForm, UserRegisterForm
from users.models import User


class ProfileUpdateView(UpdateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None): # редактировние текущего пользователя (без pk)
        return self.request.user


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = f'/users/page_after_registration/'

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save()
            self.object.is_active = False
            self.object.token = secrets.token_urlsafe(18)[:15]
            confirm_account(self.object)
            self.object.save()
            self.user_token = self.object.token
            self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self):
        new_url = super().get_success_url()
        token = self.object.token
        return str(new_url) + str(token)


def page_after_registration(request, token):
    if request.method == 'POST':
        obj = get_object_or_404(User, token=token)
        confirm_account(obj)
    return render(request, 'users/page_after_registration.html')


def activate_user(request, token):
    user = User.objects.filter(token=token).first()
    if user:
        user.is_active = True
        user.save()
        return redirect('users:login')
    return render(request, 'users/user_not_found.html')


def generate_new_password(request):
    pass_ch = secrets.token_urlsafe(18)[:9]
    send_mail(
        subject='Смена пароля',
        message=f'Ваш новый пароль {pass_ch}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    # print(pass_ch)
    request.user.set_password(pass_ch)
    request.user.save()
    return redirect(reverse('users:login'))

users/templates/users/login.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/page_after_registration.html
{% extends 'main/base.html' %}
{% block content %}
    <div class="container">
        <br>
        <h1 class="display-8">Спасибо за регистрацию!</h1>
        <br>
        <h5 class="display-8">Для подтверждения аккаунта, на почту была отправлена ссылка, перейдите по ней для
            завершения регистрации</h5>
        <form method="post">
            {% csrf_token %}
            <input class="p-2 btn btn-dark" type="submit" name="upvote" value="Отправить повторно"/>
        </form>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">  <!-- enctype="multipart/form-data" сохраняет форму и добавляет медиа(аватар) -->
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_not_found.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container">
        <br>
        <h1 class="display-8">Ошибка!</h1>
        <h1 class="display-8">Аккаунт не найден.</h1>
        <br>
        <h5 class="display-8">Возможно прошло слишком много времени с момента регистрации, попробуйте повторно перейти по ссылке из сообщения или зарегистрироваться заново</h5>
        <a class="p-2 btn btn-outline-dark" href="{% url 'users:register' %}">Рeгистрация</a>
    </div>

{% endblock %}