dz_20_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from main.apps import MainConfig
from main.views import IndexView, ProductListView, ContactView, ProductDetailView, RecordListView, RecordDetailView, \
    RecordCreateView, RecordUpdateView, RecordDeleteView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    VersionListView, CategoriesListView

app_name = MainConfig.name


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # path('', post_route)  # получение запроса из постмана
    path('contacts/', ContactView.as_view(), name='contacts'),  # Вывод url контакты  из views.py contacts
    path('products/', ProductListView.as_view(), name='products_list'),
    path('categories/', CategoriesListView.as_view(), name='categories_list'),
    path('version/', VersionListView.as_view(), name='version_list'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_item'), # url студента с переменной, в контроллере(views) так же указывается
    path('product/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('product/update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('product/delete/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='product_delete'),
    path('records/', RecordListView.as_view(), name='records_list'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_detail'),
    path('record/create/', never_cache(RecordCreateView.as_view()), name='record_create'),
    path('record/update/<int:pk>/', never_cache(RecordUpdateView.as_view()), name='record_update'),
    path('record/delete/<int:pk>/', never_cache(RecordDeleteView.as_view()), name='record_delete'),
]

main/models.py
from django.db import models
from django.urls import reverse

NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):

    ACTIV = 'Активна'
    NO_ACTIV = 'Не активна'

    SELECT_STATUS = [
        (ACTIV, 'Активна'),
        (NO_ACTIV, 'Не активна'),
    ]

    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(max_length=15000, verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='image/', verbose_name='Изображение', **NULLABLE)
    # slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    # category = models.CharField(max_length=150, verbose_name='Категория')
    category = models.ForeignKey(verbose_name='Категория', to='Category', on_delete=models.CASCADE)
    price_for_pickup = models.IntegerField(verbose_name='Цена за покупку')
    date_of_creation = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    last_modified_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')
    user = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    status = models.CharField(max_length=50, default=NO_ACTIV, choices=SELECT_STATUS, verbose_name='Статус')

    def __str__(self):
        return f'{self.name}'  #, {self.category}, {self.price_for_pickup}, {self.date_of_creation}, {self.last_modified_date}'

    # def get_absolute_url(self):
    #     return reverse('product_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ('name', 'category', 'price_for_pickup', 'date_of_creation')


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(max_length=15000, verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Record(models.Model):
    record_title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(max_length=15000, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='image/', verbose_name='Изображение', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    sign_of_publication = models.BooleanField(default=True, verbose_name='активный')
    views = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.record_title}'

    def get_absolute_url(self):
        return reverse('record_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'
        ordering = ('record_title', 'slug', 'date_of_creation', 'sign_of_publication')

    def increase_views(self):    # увеличение количества просмотров
        self.views += 1
        self.save()

    # def delete(self, *args, **kwargs):  # переопределение метода delete
    #     self.sign_of_publication = False
    #     self.save()


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.IntegerField(unique=True, verbose_name='номер версии')
    name = models.CharField(max_length=150, verbose_name='Название версии')
    sign_of_publication = models.BooleanField(default=True, verbose_name='активный')

    def __str__(self):
        return f'{self.product}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

main/forms.py
from django import forms

import dz_20_1.settings
from main.models import Product, Record, Version


class FormStyleMixin:  # стилизация формы
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(FormStyleMixin, forms.ModelForm):  # импорт форм в views.py

    class Meta:
        model = Product
        fields = '__all__'
        # fields = ('', '')
        # exclude = ('is_active', )  # исключает поле из формы

    def clean_name(self):    # валидация на слова
        cleaned_data = self.cleaned_data['name']
        for word in dz_20_1.settings.STOP_WORDS:
            if word in cleaned_data:
                raise forms.ValidationError(f'Запрещенная тематика "{word}"')
        return cleaned_data

    # def clean_first_name(self):                              # валидация на имя
    #     cleaned_data = self.cleaned_data.get('fist_name')
    #
    #     if ...:
    #         raise forms.ValidationError('Ошибка, связанная с именем пользователя')
    #
    #     return cleaned_data


class VersionForm(FormStyleMixin, forms.ModelForm):  # импорт форм в views.py

    class Meta:
        model = Version
        fields = '__all__'
        exclude = ('sign_of_publication',)  # исключает поле из формы

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from main.forms import ProductForm, VersionForm
from main.services import send_email, get_category_subjects
from main.models import Product, Record, Version, Category


class IndexView(TemplateView):
    template_name = 'main/index.html'
    extra_context = {
        'title': 'Главная страница',
        'object_list': Product.objects.filter(status='Активна')
    }


class CategoriesListView(ListView):
    model = Category
    extra_context = {
        'title': 'Все категории',
        'object_list': Category.objects.all()
    }

    def get_context_data(self, **kwargs):   # меняет title на __str__.object (имя студента)
        context_data = super().get_context_data(**kwargs)
        context_data['subject_list'] = get_category_subjects    # логика вынесена в services.py ---------
        return context_data


class ProductListView(ListView):  # выведение контекста студентов из модели по ключу object_list
    model = Product
    extra_context = {
        'object_list': Product.objects.filter(status='Активна'),
        'version_list': Version.objects.filter(sign_of_publication=True),
        'title': 'Все продукты'  # дополнение к статической информации
    }


class RecordListView(ListView):  # выведение контекста записей из модели по ключу object_list
    model = Record
    extra_context = {
        # 'object_list': Record.objects.all(),
        'title': 'Все записи',  # дополнение к статической информации
    }

    def get_queryset(self):  # выводит только активные записи
        queryset = super().get_queryset()
        queryset = queryset.filter(sign_of_publication=True)
        return queryset


class RecordDetailView(DetailView):
    model = Record

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        obj = self.get_object()
        increase = get_object_or_404(Record, pk=obj.pk)  # увеличение количества просмотров
        increase.increase_views()
        if increase.views == 100:
            send_email(increase)  # отправка письма
        return context_data


class RecordCreateView(CreateView):
    model = Record
    fields = ('record_title', 'slug', 'content', 'preview')
    success_url = reverse_lazy('main:records_list')


class RecordUpdateView(UpdateView):
    model = Record
    fields = ('record_title', 'slug', 'content', 'preview',)

    def get_success_url(self):
        return reverse('main:record_detail', args=[str(self.object.slug)])

    def get_object(self, queryset=None):     # продукт должен редактировать только владелец
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404("Вы не являетесь владельцем этого товара")
        return self.object


class RecordDeleteView(DeleteView):
    model = Record
    success_url = reverse_lazy('main:records_list')


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):  # LoginRequiredMixin требует авторизацию
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('main:products_list')

    def form_valid(self, form):           # добавление создателя
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'main/product_form_with_formset.html'
    success_url = reverse_lazy('main:products_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)  # extra= 2 выведет 2 формы
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST)  # instance=self.object выводит ещё одну форму
        else:
            context_data['formset'] = SubjectFormset()
        return context_data


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('main:products_list')


class VersionListView(ListView):
    """# выведение контекста версий из модели по ключу object_list"""
    model = Version
    extra_context = {
        'object_list': Version.objects.filter(sign_of_publication=True),
        'title': 'Все версии'
    }


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('main:products_list')


class VersionDetailView(DetailView):
    model = Version

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ContactView(TemplateView):
    template_name = 'main/contact.html'
    extra_context = {
        'title': 'Контакты'
    }

    def post(self, request, *args, **kwargs):
        """Получение данных из формы"""
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        message = request.POST.get('message', '')

        if not name or not email or not message:
            context = {"error": "Введите все поля!"}
            return render(request, self.template_name, context=context)

        print(f'Сообщение от {name}({email}): {message}')

        context = {"success": "Сообщение успешно отправлено!"}
        return render(request, self.template_name, context=context)

main/templates/main/base.html
{% load static %}  <!-- загрузка статики -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title> <!-- выводит из views.py context title ШАБЛОННУЮ ПЕРЕМЕННУЮ title -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">  <!-- Правильная загрузка статики -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>  <!-- Правильная загрузка статики -->

    <!-- ОТСТУП на 150 пикселей -->

    <style>
        main {
            margin-top: 100px;
        }
    </style>

</head>
<body>

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                {% include 'main/includes/inc_main_menu.html' %}
                <!-- ШАБЛОННЫЙ ТЕГ include вставляет отдельный html из файла inc_main_menu.html' -->
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
</header>
<main class="container marketing">
    <!-- Three columns of text below the carousel -->
    <H2> {{ title }} </H2>  <!-- выводит из views.py context title ШАБЛОННУЮ ПЕРЕМЕННУЮ title -->
    <div class="row">
        {% block content %}  <!-- выводит content из index.html -->
        {% endblock %}
    </div><!-- /.row -->
</main>

</body>
</html>

main/templates/main/category_list.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    {% for category in object_list %}
        <h6> Активная версия: {{ category.name }}</h6>
        <h6> Номер версии: {{ category.description }}</h6>
    {% endfor %}
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/contact.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <div class="col-1"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Контакты</h3>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <input class="form-control" placeholder="name" name="name"/><br><br>
                    <input class="form-control" placeholder="email" name="email" type="email"/><br><br>
                    <textarea class="form-control" placeholder="you message" name="message"></textarea><br><br>
                    <input class="btn btn-primary" type="submit" value="Отправить"/>
                </form>
            </div>
            {% if success %}
                <p>{{ success }}</p>
            {% endif %}
        </div>
    </div>
    <div class="col-5">
        <p>Moscow</p>
        <p>Москва</p>
        <p>Russian</p>
        <p>Россия</p>
    </div>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/footer.html
{% block footer %}
    <div class="row">
        <div class="col-12">
            (c) Javoprav
        </div>
    </div>
{% endblock %}

main/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <script src="/static/js/bootstrap.min.js"></script>
</head>
<body>
<div class="row mt-5">
    <div class="col-1"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Приветы!</h3>
        </div>
    </div>
</div>
</body>
</html>

main/templates/main/product.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load mediapath %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <img src="{% mediapath objects.image %}" alt="Картинка"  width="200" height="200"/>
                    <tr>
                        <td>Название</td>
                        <td>{{ objects.name }} </td>
                    </tr>
                    <tr>
                        <td>Описание</td>
                        <td>{{ objects.description }}</td>
                    </tr>
                    <tr>
                        <td>Категория</td>
                        <td>{{ objects.category }}</td>
                    </tr>
                    <tr>
                        <td>Цена:</td>
                        <td>{{ objects.price_for_pickup }}</td>
                    </tr>
                    <tr>
                        <td>Дата добавления:</td>
                        <td>{{ objects.date_of_creation }}</td>
                    </tr>
                    <tr>
                        <td>Дата обновления:</td>
                        <td>{{ objects.last_modified_date }}</td>
                    </tr>
                </table>
            </div>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            <div class="card-footer">
                <a href="{% url 'main:products_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/product_confirm_delete.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load mediapath %}
{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены что хотите удалить запись "{{ object }}"?<br> <br> <!-- <br> отступ -->
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">   <!-- ШАБЛОННЫЙ ТЕГ Условия -->
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:products_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/product_detail.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load mediapath %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <img src="{% mediapath object.image %}" alt="Картинка"  width="200" height="200"/>
                    <tr>
                        <td>Название</td>
                        <td>{{ object.name }} </td>
                    </tr>
                    <tr>
                        <td>Описание</td>
                        <td>{{ object.description }}</td>
                    </tr>
                    <tr>
                        <td>Категория</td>
                        <td>{{ object.category }}</td>
                    </tr>
                    <tr>
                        <td>Цена:</td>
                        <td>{{ object.price_for_pickup }}</td>
                    </tr>
                    <tr>
                        <td>Дата добавления:</td>
                        <td>{{ object.date_of_creation }}</td>
                    </tr>
                    <tr>
                        <td>Дата обновления:</td>
                        <td>{{ object.last_modified_date }}</td>
                    </tr>
                    <tr>
                        <td>Cоздатель:</td>
                        <td>{{ object.user }}</td>
                    </tr>
                </table>
            </div>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
            <div class="card-footer">
                <a href="{% url 'main:products_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <div class="col-12">   <!-- кнопка Создать студента -->
        <a href="{% url 'main:product_create' %}" class="btn btn-primary m-2">Создать продукт</a>
    </div>
    {% for version in version_list %}
        <h6> Активная версия: {{ version.name }}</h6>
        <h6> Номер версии: {{ version.number }}</h6>
        <h6> Продукт версии: {{ version.product }}</h6>
    {% endfor %}
    {% for object in object_list %}
        <!-- ШАБЛОННЫЙ ТЕГ for, цикл по студентам из ключа views.py context object_list -->
        {% include 'main/includes/inc_product_card.html' %} <!-- выводит подшаблон inc_student_card.html -->
    {% endfor %}   <!-- закрытие цикла for -->
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/products.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    {% for object in object_list %}
        <!-- ШАБЛОННЫЙ ТЕГ for, цикл по студентам из ключа views.py context object_list -->
        {% include 'main/includes/inc_product_card.html' %} <!-- выводит подшаблон inc_student_card.html -->
    {% endfor %}   <!-- закрытие цикла for -->
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/record_confirm_delete.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load mediapath %}
{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  Уверены что хотите удалить запись "{{ object }}"?<br> <br> <!-- <br> отступ -->
                  <input type="submit" class="btn btn-outline-danger" value="Уверен">   <!-- ШАБЛОННЫЙ ТЕГ Условия -->
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:records_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/record_detail.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->
{% load mediapath %}
{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <img src="{% mediapath object.preview %}" alt="Картинка" width="200" height="200"/>
                    <tr>
                        <td>заголовок</td>
                        <td>{{ object.record_title }} </td>
                    </tr>
                    <tr>
                        <td>Описание</td>
                        <td>{{ object.content }}</td>
                    </tr>
                    <tr>
                        <td>дата создания</td>
                        <td>{{ object.date_of_creation }}</td>
                    </tr>
                    <tr>
                        <td>Количество просмотров:</td>
                        <td>{{ object.views }}</td>
                    </tr>

                </table>
            </div>
            <a href="{% url 'main:records_list' %}" class="btn btn-primary"><< Назад</a>
        </div>
    </div>
{% endblock %}

main/templates/main/record_form.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success"
                           value="{% if object %}Сохранить{% else %} Создать {% endif %}">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:records_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->

main/templates/main/record_list.html
{% extends 'main/base.html' %} <!-- Выводит базовый html (верхняя, базовая часть сайта) -->

{% block content %}  <!-- ШАБЛОННЫЙ ТЕГ for content -->
    <div class="col-12">   <!-- кнопка Создать студента -->
        <a href="{% url 'main:record_create' %}" class="btn btn-primary m-2">Создать запись</a>
    </div>
    {% for object in object_list %}
        <!-- ШАБЛОННЫЙ ТЕГ for, цикл по студентам из ключа views.py context object_list -->
        {% include 'main/includes/inc_record_card.html' %} <!-- выводит подшаблон inc_student_card.html -->
    {% endfor %}   <!-- закрытие цикла for -->
{% endblock %}   <!-- закрытие ШАБЛОННЫЙ ТЕГ for content -->