dz_20_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from main.apps import MainConfig
from main.views import IndexView, ProductListView, ContactView, ProductDetailView, RecordListView, RecordDetailView, \
    RecordCreateView, RecordUpdateView, RecordDeleteView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    VersionListView, CategoriesListView

app_name = MainConfig.name


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    # path('', post_route)  # получение запроса из постмана
    path('contacts/', ContactView.as_view(), name='contacts'),  # Вывод url контакты  из views.py contacts
    path('products/', ProductListView.as_view(), name='products_list'),
    path('categories/', CategoriesListView.as_view(), name='categories_list'),
    path('version/', VersionListView.as_view(), name='version_list'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_item'), # url студента с переменной, в контроллере(views) так же указывается
    path('product/create/', never_cache(ProductCreateView.as_view()), name='product_create'),
    path('product/update/<int:pk>/', never_cache(ProductUpdateView.as_view()), name='product_update'),
    path('product/delete/<int:pk>/', never_cache(ProductDeleteView.as_view()), name='product_delete'),
    path('records/', RecordListView.as_view(), name='records_list'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_detail'),
    path('record/create/', never_cache(RecordCreateView.as_view()), name='record_create'),
    path('record/update/<int:pk>/', never_cache(RecordUpdateView.as_view()), name='record_update'),
    path('record/delete/<int:pk>/', never_cache(RecordDeleteView.as_view()), name='record_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import ProfileUpdateView, RegisterView, activate_user, page_after_registration, generate_new_password

app_name = UsersConfig.name


urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('activate/<str:token>/', activate_user, name='activate'),
    path('page_after_registration/<str:token>/', page_after_registration, name='page_after_registration'),
    path('profile/gennpassword', generate_new_password, name='generate_new_password'),
]

main/models.py
from django.db import models
from django.urls import reverse

NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):

    ACTIV = 'Активна'
    NO_ACTIV = 'Не активна'

    SELECT_STATUS = [
        (ACTIV, 'Активна'),
        (NO_ACTIV, 'Не активна'),
    ]

    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(max_length=15000, verbose_name='Описание', **NULLABLE)
    image = models.ImageField(upload_to='image/', verbose_name='Изображение', **NULLABLE)
    # slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    # category = models.CharField(max_length=150, verbose_name='Категория')
    category = models.ForeignKey(verbose_name='Категория', to='Category', on_delete=models.CASCADE)
    price_for_pickup = models.IntegerField(verbose_name='Цена за покупку')
    date_of_creation = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    last_modified_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')
    user = models.CharField(max_length=50, verbose_name='Создатель', **NULLABLE)
    status = models.CharField(max_length=50, default=NO_ACTIV, choices=SELECT_STATUS, verbose_name='Статус')

    def __str__(self):
        return f'{self.name}'  #, {self.category}, {self.price_for_pickup}, {self.date_of_creation}, {self.last_modified_date}'

    # def get_absolute_url(self):
    #     return reverse('product_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ('name', 'category', 'price_for_pickup', 'date_of_creation')


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.TextField(max_length=15000, verbose_name='Описание', **NULLABLE)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('name',)


class Record(models.Model):
    record_title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name="URL")
    content = models.TextField(max_length=15000, verbose_name='Содержимое')
    preview = models.ImageField(upload_to='image/', verbose_name='Изображение', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    sign_of_publication = models.BooleanField(default=True, verbose_name='активный')
    views = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.record_title}'

    def get_absolute_url(self):
        return reverse('record_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'
        ordering = ('record_title', 'slug', 'date_of_creation', 'sign_of_publication')

    def increase_views(self):    # увеличение количества просмотров
        self.views += 1
        self.save()

    # def delete(self, *args, **kwargs):  # переопределение метода delete
    #     self.sign_of_publication = False
    #     self.save()


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.IntegerField(unique=True, verbose_name='номер версии')
    name = models.CharField(max_length=150, verbose_name='Название версии')
    sign_of_publication = models.BooleanField(default=True, verbose_name='активный')

    def __str__(self):
        return f'{self.product}'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

main/forms.py
from django import forms

import dz_20_1.settings
from main.models import Product, Record, Version


class FormStyleMixin:  # стилизация формы
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(FormStyleMixin, forms.ModelForm):  # импорт форм в views.py

    class Meta:
        model = Product
        fields = '__all__'
        # fields = ('', '')
        # exclude = ('is_active', )  # исключает поле из формы

    def clean_name(self):    # валидация на слова
        cleaned_data = self.cleaned_data['name']
        for word in dz_20_1.settings.STOP_WORDS:
            if word in cleaned_data:
                raise forms.ValidationError(f'Запрещенная тематика "{word}"')
        return cleaned_data

    # def clean_first_name(self):                              # валидация на имя
    #     cleaned_data = self.cleaned_data.get('fist_name')
    #
    #     if ...:
    #         raise forms.ValidationError('Ошибка, связанная с именем пользователя')
    #
    #     return cleaned_data


class VersionForm(FormStyleMixin, forms.ModelForm):  # импорт форм в views.py

    class Meta:
        model = Version
        fields = '__all__'
        exclude = ('sign_of_publication',)  # исключает поле из формы

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.http import Http404
from django.shortcuts import render, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from main.forms import ProductForm, VersionForm
from main.services import send_email, get_category_subjects
from main.models import Product, Record, Version, Category


class IndexView(TemplateView):
    template_name = 'main/index.html'
    extra_context = {
        'title': 'Главная страница',
        'object_list': Product.objects.filter(status='Активна')
    }


class CategoriesListView(ListView):
    model = Category
    extra_context = {
        'title': 'Все категории',
        'object_list': Category.objects.all()
    }

    def get_context_data(self, **kwargs):   # меняет title на __str__.object (имя студента)
        context_data = super().get_context_data(**kwargs)
        context_data['subject_list'] = get_category_subjects    # логика вынесена в services.py ---------
        return context_data


class ProductListView(ListView):  # выведение контекста студентов из модели по ключу object_list
    model = Product
    extra_context = {
        'object_list': Product.objects.filter(status='Активна'),
        'version_list': Version.objects.filter(sign_of_publication=True),
        'title': 'Все продукты'  # дополнение к статической информации
    }


class RecordListView(ListView):  # выведение контекста записей из модели по ключу object_list
    model = Record
    extra_context = {
        # 'object_list': Record.objects.all(),
        'title': 'Все записи',  # дополнение к статической информации
    }

    def get_queryset(self):  # выводит только активные записи
        queryset = super().get_queryset()
        queryset = queryset.filter(sign_of_publication=True)
        return queryset


class RecordDetailView(DetailView):
    model = Record

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        obj = self.get_object()
        increase = get_object_or_404(Record, pk=obj.pk)  # увеличение количества просмотров
        increase.increase_views()
        if increase.views == 100:
            send_email(increase)  # отправка письма
        return context_data


class RecordCreateView(CreateView):
    model = Record
    fields = ('record_title', 'slug', 'content', 'preview')
    success_url = reverse_lazy('main:records_list')


class RecordUpdateView(UpdateView):
    model = Record
    fields = ('record_title', 'slug', 'content', 'preview',)

    def get_success_url(self):
        return reverse('main:record_detail', args=[str(self.object.slug)])

    def get_object(self, queryset=None):     # продукт должен редактировать только владелец
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404("Вы не являетесь владельцем этого товара")
        return self.object


class RecordDeleteView(DeleteView):
    model = Record
    success_url = reverse_lazy('main:records_list')


class ProductDetailView(DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ProductCreateView(LoginRequiredMixin, CreateView):  # LoginRequiredMixin требует авторизацию
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('main:products_list')

    def form_valid(self, form):           # добавление создателя
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'main/product_form_with_formset.html'
    success_url = reverse_lazy('main:products_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)  # extra= 2 выведет 2 формы
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST)  # instance=self.object выводит ещё одну форму
        else:
            context_data['formset'] = SubjectFormset()
        return context_data


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('main:products_list')


class VersionListView(ListView):
    """# выведение контекста версий из модели по ключу object_list"""
    model = Version
    extra_context = {
        'object_list': Version.objects.filter(sign_of_publication=True),
        'title': 'Все версии'
    }


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('main:products_list')


class VersionDetailView(DetailView):
    model = Version

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = self.get_object()
        return context_data


class ContactView(TemplateView):
    template_name = 'main/contact.html'
    extra_context = {
        'title': 'Контакты'
    }

    def post(self, request, *args, **kwargs):
        """Получение данных из формы"""
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        message = request.POST.get('message', '')

        if not name or not email or not message:
            context = {"error": "Введите все поля!"}
            return render(request, self.template_name, context=context)

        print(f'Сообщение от {name}({email}): {message}')

        context = {"success": "Сообщение успешно отправлено!"}
        return render(request, self.template_name, context=context)

main/templates/main/includes/inc_main_menu.html
<ul class="navbar-nav me-auto mb-2 mb-md-0">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Главная</a>
        <!-- динамическая ссылка на url -->
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'main:products_list' %}">Все товары</a>  <!-- динамическая ссылка на url -->
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'main:records_list' %}">Записи</a>  <!-- динамическая ссылка на url -->
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'main:categories_list' %}">Категории</a>  <!-- динамическая ссылка на url -->
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'main:contacts' %}">Контакты</a>  <!-- динамическая ссылка на url -->
    </li>
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>  <!-- динамическая ссылка на url -->
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>  <!-- динамическая ссылка на url -->
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>  <!-- динамическая ссылка на url -->
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>  <!-- динамическая ссылка на url -->
        </li>
    {% endif %}
</ul>

main/templates/main/includes/inc_product_card.html
{% load mediapath %}
<div class="col-lg-4">
    <div class="card m-2 text-center">
        <div class="card-body">
            <img src="{% mediapath object.image %}" alt="Картинка" width="200" height="200"/>
            <h2>{{ object.name|title }} </h2>
            <h6> {{ object.description|slice:":100" }}</h6>  <!--Фильтр slice получает часть списка.-->
            <h4> {{ object.price_for_pickup|title }}</h4>
            <p><a class="btn btn-secondary" href="{% url 'main:product_item' object.pk %}">Посмотреть &raquo;</a></p>
            {% if user.is_authenticated and object.user == user.email %}
                <p><a class="btn btn-warning" href="{% url 'main:product_update' object.pk %}">Изменить &raquo;</a></p>
                {% if user.is_superuser %}
                <p><a class="btn btn-danger" href="{% url 'main:product_delete' object.pk %}">Удалить &raquo;</a></p>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div><!-- /.col-lg-4 -->

main/templates/main/includes/inc_record_card.html
{% load mediapath %}
<div class="col-lg-4">
    <div class="card m-2 text-center">
        <div class="card-body">
            <img src="{% mediapath object.preview %}" alt="Картинка" width="200" height="200"/>
            <h2>{{ object.record_title|title }} </h2>
            <h6> {{ object.content|slice:":100" }}</h6>  <!--Фильтр slice получает часть списка.-->

            <!-- —ШАБЛОННЫЕ ПЕРЕМЕННЫЕ В заголовок выводятся имена из цикла по ключу -->
            <p><a class="btn btn-secondary" href="{% url 'main:record_detail' object.slug %}">Посмотреть &raquo;</a></p>
            <p><a class="btn btn-warning" href="{% url 'main:record_update' object.pk %}">Изменить &raquo;</a></p>
            {% if user.is_superuser %}
                <p><a class="btn btn-danger" href="{% url 'main:record_delete' object.pk %}">Удалить &raquo;</a></p>
            {% endif %}
        </div>
    </div>
</div><!-- /.col-lg-4 -->